name: docker-desktop-test
on:
  workflow_dispatch:
    inputs:
      RUN_TIME:
        description: "RUN_TIME"
        required: true
        default: 2h

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Configure environment and setup desktop
        run: |
          sudo apt update
          sudo apt install curl iproute2 
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
          docker run cloudflare/cloudflared:latest tunnel --no-autoupdate run --token ${{secrets.CLOUDFLARED_TOKEN}}
          docker run -p 8080:80 dorowu/ubuntu-desktop-lxde-vnc

      - name: Don't kill instace
        run: sleep ${{github.event.inputs.RUN_TIME}} # Prevent to killing instance after failure
