name: docker-desktop-test
on:
  workflow_dispatch:
    inputs:
      RUN_TIME:
        description: "RUN_TIME"
        required: true
        default: 2h

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Configure environment and setup desktop
        run: |
          sudo apt update
          sudo apt install curl iproute2 
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
          wget -O cloudflared.deb https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb && 
          sudo dpkg -i cloudflared.deb
          cloudflared tunnel --url http://localhost:80 --no-autoupdate > argo.log 2>&1 &
          argo_url=$(cat argo.log | grep -oE "https://.*[a-z]+cloudflare.com" | sed "s#https://##") | echo -
          echo $argo_url
          docker run -p 8080:80 dorowu/ubuntu-desktop-lxde-vnc

      - name: Don't kill instace
        run: sleep ${{github.event.inputs.RUN_TIME}} # Prevent to killing instance after failure
