name: docker-desktop-test
on:
  workflow_dispatch:
    inputs:
      RUN_TIME:
        description: "RUN_TIME"
        required: true
        default: 2h

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Configure environment and setup desktop
        run: |
          sudo apt update
          sudo apt install curl iproute2 
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
          sudo docker run -d --name=webtop -e PUID=1000 -e PGID=1000 -e TZ=Europe/London -p 3000:3000 -v /path/to/data:/config --shm-size="1gb" --restart unless-stopped ghcr.io/linuxserver/webtop 
          docker run cloudflare/cloudflared:latest tunnel --no-autoupdate run --token ${{secrets.CLOUDFLARED_TOKEN}}

      - name: Don't kill instace
        run: sleep ${{github.event.inputs.RUN_TIME}} # Prevent to killing instance after failure
